version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
       - 5434:5432
    environment:
      POSTGRES_USER: nexstack
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest
    networks:
      - deevoe

networks:
  deevoe:
